python main.py \
    --ignore-search summary \
    --batch-size 48 \
    --epochs 700 \
    --optimizer adam \
    --lr 0.01 \
    --lr-mode cosine \
    --lr-warmup 5 \
    --loss supcon \
    --standardize norm \
    --checkpoint \
    --history \
    --data-path /workspace/data2/Dataset/cub/ \
    --gpus 0,1,2,3
